### ISSUE TITLE
Integrating with Boost.Property_tree

### ISSUE THREAD

**Issue by zamazan4ik** [nlohmann/std_json#2]
Hello.

I have seen your proposal to C++ standard library. Very nice!

I want to work in the same way. I think you know about 
Boost.Property_tree. It's universal library for working with json, xml, 
ini and other formats. And i want see smth like this in the C++. What do 
you think about the idea?

Best regards,

Alexander Zaitsev

**Comment by mariokonrad** [comment]
Thanks!

I'm afraid, I do not know Boost.Property_tree well, I've never used it.

Maybe you'd like to post in [this](https://groups.google.com/a/isocpp.org/forum/?fromgroups#!forum/std-proposals) forum and get some (maybe scary) feedback. Please take the feedback there with a grain of salt...

Best Regards,
Mario

**Comment by zamazan4ik** [comment]
Good, nice idea. Let's talk in Google group :-)

I think, it's the right link: https://groups.google.com/a/isocpp.org/forum/?fromgroups=#!searchin/std-proposals/json/std-proposals/JNZzOvC7llo/yAo_xaLGCQAJ

**Comment by mariokonrad** [comment]
Oh, I apologize. I most probably misunderstood (I thought you'd like to write a proposal for having Boost.Property_Tree in the standard).

There is no plan to merge/integrate this (JSON) proposal with Boost.Property_Tree, nor would I advocate such a plan. It would extend the scope of the proposal too much, and personally, I'm not very interested in Boost.Property_Tree.

**Comment by zamazan4ik** [comment]
I simpoly try to find some way to add general solution for libraries which works with formats like XML, JSON, etc.

I thought can become solution here. I just ask you advice - is it real try to find a lot of general between XML/JSON/INI formats?

**Comment by nlohmann** [comment]
I think JSON is much simpler than XML, and this standardization approach bases on the experience of the nlohmann/json implementation. I doubt that it is a good idea to "just" add INI and XML just because we may share a tree structure.

**Comment by zamazan4ik** [comment]
If you can *just* add, my question is answered :)

**Comment by nlohmann** [comment]
I think it's out of scope.

**Comment by mariokonrad** [comment]
Seconded.

Closing the issue.
