### ISSUE TITLE
P0939R4 -- JSON is one of the priorities -- WG21 need a better categorization

### ISSUE THREAD

**Issue by DBJDBJ** [nlohmann/std_json#20]
I would like to adopt this document as a guidance. It is also (very) honest doc, describing the mess WG21 is in. 

Consequently is it **very** hard to "push the paper through".   What is also contains is very useful advice on how to write papers and what to put forward so that paper is (hopefully) approved. 

Page 7. JSON is mentioned in a context perhaps not explicitly explained in our paper.
_"... However here are some areas of general concerns – often cutting across application domains – that we should not ignore:..."

But then JSON is somewhat buried (although mentioned) under a wrong context:

_"... Support for demanding applications: offer domain-specific support for important application
areas, such as medical, finance, automotive, and games (e.g., key libraries, such as JSON, flat
containers, and pool and stack allocators). .."_

JSON (as we know and everybody else knows) is essential for app/system to be operational "across application domains" ...

JSON is essential for Interoperability ... Just a paragraph above ... In any case, the general tone of page 7 (for me) says the JSON is a priority. Even if it is wrongly categorised.

**Comment by mariokonrad** [comment]
Sorry for the long delay. I agree fully.

**Comment by DBJDBJ** [comment]
It's good to talk :)  I am accidentally, (sigh) now more involved than I would like into SIMDJSON (SJ) ...

Yet another (use-)case of mistaken identity. Which comes from lack of categorization. SJ to std_json is comparing apples and pears. Nobody cares until they hit their collective foot. Including "rapid json" etc. They use irrelevant measures and have no clear real-life use cases.  Not to mention, huge code base full of C code in cpp files. Good people and good code but not modern C++.

There is no better json lib mature for standardization than this one.  We just need to make that obvious. And even if WG21 proves (yet again) as a "stone wall",  std_json should/would be a de-facto standard.
