### ISSUE TITLE
Why is Json object a map and not a variant or union type.

### ISSUE THREAD

**Issue by ghost** [nlohmann/std_json#4]
Why is it a map rather than a variant or union ? Doesn't make sense to keep it so.

**Comment by ghost** [comment]
As an addendum. I am opening this issue, due to the concern of performance for when nesting takes places with object that contains objects.

Bjorn Reese's suggestion for hetrogenous containers seems like a needed requirement.

**Comment by nlohmann** [comment]
What is your proposal to improve performance when it comes to nesting of objects?

**Comment by ghost** [comment]
sadly I have none. :(
was hoping you guys might have had some thoughts for why std::map ...

**Comment by mariokonrad** [comment]
`basic_json` is a template, `std::map` is just the default type for the object type. The option you would have is to use a different type, like: `using my_json = basic_json<..., my_fast_flat_map, ...>`, as long
as `my_fast_flat_map` meets the requirements (which are not formulated in the proposal yet).

And please note:
- The proposal is nowhere near finished.
- The proposal specifies behavior, API, etc. and not a specific implementation.
- The proposal is based on Niels' library, therefore based on field experience. If you have input or a PR on how to make things faster/smaller/stronger/better, I'm sure you are most welcome.
