### ISSUE TITLE
[comment] Consider sending to LEWG without all the detailed wording

### ISSUE THREAD

**Issue by ldionne** [nlohmann/std_json#7]
I would suggest that the paper be sent to LEWG without necessarily including all the detailed wording. Indeed, if it happened that LEWG said "no" right away, then you'd save a bunch of time on the wording. If there's preliminary feedback from LEWG, you'll also save time not needing to update the wording.

Not all proposals come with fully detailed wording the first time around; I think it is more useful to start iterating on this proposal early than to wait for the thing to be fully worded and only then to start iterating on the design with LEWG. I would love to see this as soon as Albuquerque.

**Comment by mariokonrad** [comment]
Thank you for the input! First time writing a proposal... still clumsy ;-)

I think, with sending the proposal early to LEWG, there probably needs to be more work done in the "Motivation" and maybe "Example" section, to "sell" it better to the group. Maybe not the detailed wording of everything, but text about intention and motivation...

The meeting in Albuquerque is in november. In your experience, how far ahead would the proposal need to be submitted to be included in the schedule of the meeting?

**Comment by ldionne** [comment]
> I think, with sending the proposal early to LEWG, there probably needs to be more work done in the "Motivation" and maybe "Example" section, to "sell" it better to the group. 

Yes, I think that's the right approach. Great motivation and examples go a __long__ way towards convincing people, much more than fully baked wording does. I would recommend focusing on motivation, examples, and a synopsis of the functionality you plan to provide along with the design decisions that make your proposal distinct from another (hypothetical) JSON proposal.

> The meeting in Albuquerque is in november. In your experience, how far ahead would the proposal need to be submitted to be included in the schedule of the meeting?

The deadline for the pre-meeting mailing for Albuquerque is Monday October 16, 2017 (I think it's 8:00 AM EST). It's always about 3 weeks before the meeting, IIRC.

**Comment by mariokonrad** [comment]
> The deadline for the pre-meeting mailing for Albuquerque is Monday October 16, 2017 (I think it's 8:00 AM EST). It's always about 3 weeks before the meeting, IIRC.

Is it required for the proposal to already have a P number before the deadline? I try to find the information on https://isocpp.org/std, but to me it is not entirely clear, who issues when the P number, if the proposal is even supposed to get one.

**Comment by mariokonrad** [comment]
> The deadline for the pre-meeting mailing for Albuquerque is Monday October 16, 2017 (I think it's 8:00 AM EST). It's always about 3 weeks before the meeting, IIRC.

Is it required for the proposal to already have a P number before the deadline? I try to find the information on https://isocpp.org/std, but to me it is not entirely clear, who issues when the P number, if the proposal is even supposed to get one.

**Comment by ldionne** [comment]
Yes, a P number is required to be included in the mailing. I'll send you the email of the person you should contact to request a number. I'm not sure whether that's supposed to be shared publicly.

**Comment by mariokonrad** [comment]
Thank you very much, I appreciate your help!

Got your eMail, will do it this week. Thanks again!

**Comment by ldionne** [comment]
Closing this, as the original comment has clearly been heard.
